# -*- coding: utf-8 -*-
"""abc.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GrWpMyuBtnHLp9NgQZQnyeZyvX3Xe7v3
"""

def func(a):
  print(a)
studentone = {
  "name": "Ali",
  "family": "Ahmadi",
  "age": 36,
  "weight": 85,
  "country": "Iran"
}
a=9

print(studentone)